# Generated by Django 3.2.6 on 2021-08-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Teams', 'verbose_name_plural': 'Teams'},
        ),
    ]
