# Generated by Django 3.2.6 on 2021-08-25 11:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('bike_photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bike_photo1', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bike_photo2', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bike_photo3', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bike_photo4', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bike_photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Integrated Braking System', 'Integrated Braking System'), ('i3s Technology', 'i3s Technology'), ('Speedometer', 'Speedometer'), ('Odometer', 'Odometer'), ('Tripmeter', 'Tripmeter'), ('Alarm System', 'Alarm System'), ('Passenger Footrest', 'Passenger Footrest'), ('Power Steering', 'Power Steering'), ('XSens Technology', 'XSens Technology'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector')], max_length=200)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('brakes', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('miles', models.IntegerField()),
                ('vin_no', models.CharField(max_length=150)),
                ('milage', models.IntegerField()),
                ('No_of_cylinders', models.IntegerField()),
                ('fuel_capacity', models.CharField(max_length=50)),
                ('tyre_type', models.CharField(max_length=50)),
                ('No_of_owners', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
